services:
  # java_app:
  #   container_name: java_app
  #   image: pee-java_app:1.0.0
  #   build: .
  #   ports:
  #     - 8080:8080
  #   environment:
  #     - DATABASE_URL=jdbc:postgresql://java_db:5432/KioskTV
  #     - DATABASE_USERNAME=admin
  #     - DATABASE_PASSWORD=admin
  #   depends_on:
  #     - java_db
  
  java_db:
    container_name: java_db
    image: postgres
    ports:
      - 5051:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: KioskTV